<div id="termsOfService">
<p>
    The following terms and conditions govern all use of the <a href="http://www.earthexplorer.info">EARTHEXPLORER.INFO</a> website and all content, services and products available at or through the website (taken together, the Website). The Website is owned and operated by <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>. The Website is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies and procedures that may be published from time to time on this Site by <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> (collectively, the “Agreement”).
</p>
<hr/>

<p>
    Please read this Agreement carefully before accessing or using the web site. By accessing or using any part of the web site, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access the website or use any services. If these terms and conditions are considered an offer by <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>, acceptance is expressly limited to these terms.
</p>

<h2>Your Account</h2>
<p>
    You are responsible for maintaining the security of your account, and you are fully responsible for all activities that occur under the account and any other actions taken in connection with it. You must not use your account in a misleading or unlawful manner, including in a manner intended to trade on the name or reputation of others, and <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> may change or remove any description or keyword that it considers inappropriate or unlawful, or otherwise likely to cause <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> liability. You must immediately notify <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> of any unauthorized uses of your account or any other breaches of security. <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> will not be liable for any acts or omissions by You, including any damages of any kind incurred as a result of such acts or omissions.
</p>
<h2>Responsibility of Contributors</h2>
<p>
    If you operate a blog, comment on a blog, post material to the Website, post links on the Website, or otherwise make (or allow any third party to make) material available by means of the Website (any such material, “Content”), You are entirely responsible for the content of, and any harm resulting from, that Content. That is the case regardless of whether the Content in question constitutes text, graphics, an audio file, or computer software. By making Content available, you represent and warrant that:
</p>
<ul>
    <li>the downloading, copying and use of the Content will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark or trade secret rights, of any third party;</li><li>if your employer has rights to intellectual property you create, you have either (i) received permission from your employer to post or make available the Content, including but not limited to any software, or (ii) secured from your employer a waiver as to all rights in or to the Content;</li><li>you have fully complied with any third-party licenses relating to the Content, and have done all things necessary to successfully pass through to end users any required terms;</li><li>the Content does not contain or install any viruses, worms, malware, Trojan horses or other harmful or destructive content;</li><li>the Content is not spam, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or boost the search engine rankings of third party sites, or to further unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing);</li><li>the Content is not obscene, libelous or defamatory (more info on what that means), hateful or racially or ethnically objectionable, and does not violate the privacy or publicity rights of any third party; and</li><li>you have, in the case of Content that includes computer code, accurately categorized and/or described the type, nature, uses and effects of the materials, whether requested to do so by <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> or otherwise.</li>
</ul>
<p>
    By submitting Content to <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> for inclusion on your Website, you grant <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> a world-wide, royalty-free, and non-exclusive license to reproduce, modify, adapt and publish the Content solely for the purpose of displaying, distributing and promoting your blog. If you delete Content, <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> will use reasonable efforts to remove it from the Website, but you acknowledge that caching or references to the Content may not be made immediately unavailable.
</p>
<p>
    Without limiting any of those representations or warranties, <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> has the right (though not the obligation) to, in <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>’s sole discretion (i) refuse or remove any content that, in <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>’s reasonable opinion, violates any <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> policy or is in any way harmful or objectionable, or (ii) terminate or deny access to and use of the Website to any individual or entity for any reason, in <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>’s sole discretion. <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> will have no obligation to provide a refund of any amounts previously paid.
</p>
<h2>Fees and Payment</h2>
<p>
    Optional premium paid services are available on the Website. By selecting a premium service you agree to pay <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> the monthly or annual subscription fees indicated for that service. Payments will be charged on the day you sign up for a premium service and will cover the use of that service for a monthly or annual period as indicated. Premium service fees are not refundable.
</p>
<h2>Premium Services</h2>
<ul>
    <li>Fees; Payment. By signing up for a premium account you agree to pay <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> the setup fees and monthly hosting fees indicated at <a href="YOUR URL">YOUR URL</a> in exchange for the services listed at <a href="YOURURL">YOURURL</a>. Applicable fees will be invoiced starting from the day your services are established and in advance of using such services. <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> reserves the right to change the payment terms and fees upon thirty (30) days prior written notice to you. Services can be canceled by you at anytime on 30 days written notice to <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>.</li><li>Support. VIP Services include access to priority email support. “Email support” means the ability to make requests for technical support assistance by email at any time (with reasonable efforts by <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> to respond within one business day) concerning the use of the Services. “Priority” means that support for Services customers takes priority over support for users of the standard, free services. All Services support will be provided in accordance with <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> standard Services practices, procedures and policies.</li>
</ul>

<h2>Responsibility of Website Visitors</h2>
<p>
    <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> has not reviewed, and cannot review, all of the material, including computer software, posted to the Website, and cannot therefore be responsible for that material’s content, use or effects. By operating the Website, <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> does not represent or imply that it endorses the material there posted, or that it believes such material to be accurate, useful or non-harmful. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. The Website may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. The Website may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstated. <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> disclaims any responsibility for any harm resulting from the use by visitors of the Website, or from any downloading by those visitors of content there posted.
</p>
<h2>Content Posted on Other Websites</h2>
<p>
    We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which <a href="http://www.earthexplorer.info/">EARTHEXPLORER.INFO</a> links, and that link to <a href="http://www.earthexplorer.info/">EARTHEXPLORER.INFO</a>. <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> does not have any control over those non-<a href="http://www.earthexplorer.info/">EARTHEXPLORER.INFO</a> websites and webpages, and is not responsible for their contents or their use. By linking to a non-<a href="http://www.earthexplorer.info/">EARTHEXPLORER.INFO</a> website or webpage, <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> disclaims any responsibility for any harm resulting from your use of non-<a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> websites and webpages.
</p>
<h2>Copyright Infringement and DMCA Policy</h2>
<p>
    As <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> asks others to respect its intellectual property rights, it respects the intellectual property rights of others. If you believe that material located on or linked to by <a href="http://www.earthexplorer.info/">EARTHEXPLORER.INFO</a> violates your copyright, you are encouraged to notify <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> in accordance with <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>’s Digital Millennium Copyright Act (”DMCA”) Policy. <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> will respond to all such notices, including as required or appropriate by removing the infringing material or disabling all links to the infringing material. In the case of a visitor who may infringe or repeatedly infringes the copyrights or other intellectual property rights of <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> or others, <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> may, in its discretion, terminate or deny access to and use of the Website. In the case of such termination, <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> will have no obligation to provide a refund of any amounts previously paid to <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>.
</p>
<h2>Intellectual Property</h2>
<p>
    This Agreement does not transfer from <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> to you any <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> or third party intellectual property, and all right, title and interest in and to such property will remain (as between the parties) solely with <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>. <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>, <a href="YOUR TRADEMARKS AND URL">YOUR TRADEMARKS AND URL</a>, and all other trademarks, service marks, graphics and logos used in connection with <a href="http://www.earthexplorer.info/">EARTHEXPLORER.INFO</a>, or the Website are trademarks or registered trademarks of <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> or <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>’s licensors. Other trademarks, service marks, graphics and logos used in connection with the Website may be the trademarks of other third parties. Your use of the Website grants you no right or license to reproduce or otherwise use any <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> or third-party trademarks.
</p>
<h2>Changes</h2>
<p>
    <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> reserves the right, at its sole discretion, to modify or replace any part of this Agreement. It is your responsibility to check this Agreement periodically for changes. Your continued use of or access to the Website following the posting of any changes to this Agreement constitutes acceptance of those changes. <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> may also, in the future, offer new services and/or features through the Website (including, the release of new tools and resources). Such new features and/or services shall be subject to the terms and conditions of this Agreement.
</p>
<h2>Termination</h2>
<p>
    <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> may terminate your access to all or any part of the Website at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement or your account (if you have one), you may simply discontinue using the Website. Notwithstanding the foregoing, if you have a Services account, such account can only be terminated by <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> if you materially breach this Agreement and fail to cure such breach within thirty (30) days from <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>’s notice to you thereof; provided that, <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> can terminate the Website immediately as part of a general shut down of our service. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.
</p>
<h2>Disclaimer of Warranties</h2>
<p>
    The Website is provided “as is”. <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> nor its suppliers and licensors, makes any warranty that the Website will be error free or that access thereto will be continuous or uninterrupted. If you’re actually reading this, here’s a treat <a href="LINK TO YOUR TREAT HERE OR REMOVE THIS SECTION IF YOU HAVE NO SENSE OF HUMOUR">LINK TO YOUR TREAT HERE OR REMOVE THIS SECTION IF YOU HAVE NO SENSE OF HUMOUR</a>. You understand that you download from, or otherwise obtain content or services through, the Website at your own discretion and risk.
</p>
<h2>Limitation of Liability</h2>
<p>
    In no event will <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>, or its suppliers or licensors, be liable with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damagaes; (ii) the cost of procurement or substitute products or services; (iii) for interpution of use or loss or corruption of data; or (iv) for any amounts that increase the fees paid by you to <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> under this agreement during the twelve (12) month period prior to the date the cause of the action accrues. <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law.
</p>
<h2>General Representation and Warranty</h2>
<p>
    You represent and warrant that (i) your use of the Website will be in strict accordance with the <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> Privacy Policy, with this Agreement and with all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the United States or the country in which you reside) and (ii) your use of the Website will not infringe or misappropriate the intellectual property rights of any third party.
</p>
<h2>Indemnification</h2>
<p>
    You agree to indemnify and hold harmless <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>, its contractors, and its licensors, and their respective directors, officers, employees and agents from and against any and all claims and expenses, including attorneys’ fees, arising out of your use of the Website, including but not limited to out of your violation this Agreement.
</p>
<h2>Miscellaneous</h2>
<p>This Agreement constitutes the entire agreement between <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a>, or by the posting by <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> of a revised version. Except to the extent applicable law, if any, provides otherwise, this Agreement, any access to or use of the Website will be governed by the laws of the state of <a href="http://www.earthexplorer.info/Explore/23424748-Australia-Country-Australia">AUSTRALIA</a>, excluding its conflict of law provisions, and the proper venue for any disputes arising out of or relating to any of the same will be the state and federal courts located in <a href="http://www.earthexplorer.info/Explore/2344700-New-South-Wales-State-Australia">NEW SOUTH WALES, AUSTRALIA</a>.
</p>
<!--
<p>
    <a href="THIS SECTION MAY NOT APPLY TO YOU">THIS SECTION MAY NOT APPLY TO YOU</a> Except for claims for injunctive or equitable relief or claims regarding intellectual property rights (which may be brought in any competent court without the posting of a bond), any dispute arising under this Agreement shall be finally settled in accordance with the Comprehensive Arbitration Rules of the Judicial Arbitration and Mediation Service, Inc. (“JAMS”) by three arbitrators appointed in accordance with such Rules. The arbitration shall take place in San Francisco, California, in the English language and the arbitral decision may be enforced in any court.
</p>
<p>
    The prevailing party in any action or proceeding to enforce this Agreement shall be entitled to costs and attorneys’ fees. If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties’ original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; <a href="http://www.alchemycs.net.au">Alchemy Computer Solutions</a> may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.
</p>
-->
</div>