<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
*/

class WOEIDRoutingCallback extends AgaviRoutingCallback {

    /**
     * Gets executed when the route of this callback route matched.
     *
     * @param      array                   The parameters generated by this route.
     * @param      AgaviExecutionContainer The original execution container.
     *
     * @return     bool Whether the routing should handle the route as matched.
     *
     * @author     Dominik del Bondio <ddb@bitxtender.com>
     * @since      0.11.0
     */
    public function onMatched(array &$parameters, AgaviExecutionContainer $container) {

        $woeid = $parameters['woeid'];

        if (is_null($woeid)) {
            return false;
        }


        $placeFinder = $this->getContext()->getModel('PlaceFinder', 'Explorer');
        $place = $placeFinder->findByWoeid($woeid);

        if (is_null($place)) {
            return false;
        }

        $container->setAttribute('placeFinder', $placeFinder);
        $container->setAttribute('place', $place);
        
        return true;
    }

    /**
     * Gets executed when the route of this callback route did not match.
     *
     * @param      AgaviExecutionContainer The original execution container.
     *
     * @author     Dominik del Bondio <ddb@bitxtender.com>
     * @since      0.11.0
     */
    public function onNotMatched(AgaviExecutionContainer $container) {
        return;
    }

    /**
     * Gets executed when the route of this callback is about to be reverse
     * generated into an URL.
     *
     * @param      array The default parameters stored in the route.
     * @param      array The parameters the user supplied to AgaviRouting::gen().
     * @param      array The options the user supplied to AgaviRouting::gen().
     *
     * @return     bool  Whether this route part should be generated.
     *
     * @author     Dominik del Bondio <ddb@bitxtender.com>
     * @since      0.11.0
     */
    public function onGenerate(array $defaultParameters, array &$userParameters, array &$userOptions) {
        return true;
    }


}

?>
